language: php

services:
    - redis-server

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

sudo: false

before_script:
    - if [[ ! $TRAVIS_PHP_VERSION = hhvm* ]]; then INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; else INI_FILE=/etc/hhvm/php.ini; fi
    - echo "extension = redis.so" >> $INI_FILE
    - travis_retry composer self-update
    - travis_retry composer install ${COMPOSER_FLAGS} --no-interaction

script:
    - mkdir -p build/logs
    - php vendor/bin/phpcs src tests --standard=PSR2 -n
    - php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
